# Flux Plugin configuration
# Reload the plugin using /nlpl reload

api:
  # Enable the API and obtain the API URL and API key in StaffCP > Configuration > API
  url: ""
  key: ""
  # Print detailed information about website requests and responses
  debug: false
  # Maximum time in milliseconds to wait for a response from the website
  # Set to 10 seconds for slower webservers. Sensible values are 3s-15s.
  timeout: 5000
  # Use usernames instead of UUIDs to identify players. This allows some parts of the plugin to work for
  # offline mode / "cracked" servers. Do not enable this if your server is in online mode or your server is connected
  # to a proxy (bungeecord/velocity) that is in online mode. No support will be given with this option enabled, use
  # at your own risk!
  usernames: false

# The server data sender sends data about this server to the website, periodically. It is essential for many
# features to work like group sync, username sync and placeholders.
# Note that currently the website doesn't use the plugin for server status and player list yet, even though
# the plugin sends this information. You'll need to configure server pinging separately on the website.
server-data-sender:
  enabled: false
  # Find your server id in StaffCP > Integrations > Minecraft > Minecraft Servers
  # Create a server if you haven't already
  server-id: 0
  # Interval in seconds. Reasonable values are 2-30 seconds.
  interval: 10
  # Send PlaceholderAPI placeholders, to be used by Flux Networks (leaderboards, profile pages) or modules.
  placeholders:
    enabled: false
    # global placeholders to send to the website (list of placeholder names without %%). Not currently used by the website.
    global: []
    # player-specific placeholders to send to the website (list of placeholder names without %%)
    player: []

# Retrieving user info from Flux Networks and make it available as PlaceholderAPI placeholders.
# NOT the same as sending placeholders to the website, which can be configured above!
retrieve-placeholders:
  enabled: false
  # Update interval in seconds
  interval: 30


# Number of milliseconds in between notifications request
# Lower number means more frequent updates of placeholders, but higher
# network usage.
placeholders-request-delay: 2000

# Show single line error messages instead of full stacktraces.
# Can be helpful to reduce console spam while your webserver is broken.
single-line-exceptons: false

# Send a message to players who don't have a Flux Networks account when they join
not-registered-join-message: false

# When a player is banned, also ban their website account if they have one.
auto-ban-on-website: false

# For a list of valid languages, check file names in the 'languages' directory.
# If you want to customize messages for your server you can edit the language files.
# WARNING: The language file will be replaced with the default when new messages are added in a plugin update
language: en_UK

user-sync:
  # Number of seconds in between syncs
  poll-interval: 30
  log: true
  # List of UUIDs to exclude (never add to or remove from the whitelist or ban list)
  # These UUIDs must be written with dashes. If you've enabled api-usernames, enter usernames instead.
  exclude: []

  # Auto whitelist registered players.
  #
  # When enabled, the plugin will automatically whitelist players that are registered on the website.
  # Warning: Anyone who is not registered on the website will be removed from the whitelist, also
  # if they were added before enabling this option!
  whitelist:
    enabled: false
    # Only whitelist verified users
    verified-only: false
    # Only whitelist users with a linked Discord account
    # https://github.com/IncasedDevelopment/Flux-Link/wiki/Setup
    discord-linked-only: false

  # Ban players who are banned on the website, and pardon players who are not banned on the website.
  bans:
    enabled: false

# Periodically send website announcements in chat
announcements:
  # Every <interval> minutes a random announcement is chosen (if there are any) and sent to the player
  # Set to 0 to disable
  interval: 0
  # If specified, it will only show announcements with the respective display.
  # see https://github.com/IncasedDevelopment/Flux-Link/wiki/v2-API#getannouncements-get
  # display: Forums

# Run commands sent by the Websend module (third party)
# For this to work you must also configure the server id in the 'server-data-sender' section. However, websend
# is unrelated to the server data sender and the server data sender doesn't have to be enabled.
websend:
  # Poll the Websend module for commands to execute
  command-executor:
    enabled: false
    interval: 2
  # EXPERIMENTAL: Send console output to the Websend module
  console-capture:
    enabled: false
    send-interval: 2
